In [15]:
#importing required packages

In [4]:
 pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
pip install quandl

Collecting quandl
  Using cached Quandl-3.7.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from quandl) (1.16.0)
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from quandl) (2.8.2)
Collecting more-itertools
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
Requirement already satisfied: numpy>=1.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from quandl) (1.22.4)
Collecting inflection>=0.3.1
  Using cached inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Requirement already satisfied: pandas>=0.14 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from quandl) (1.4.2)
Requirement already satisfied: requests>=2.7.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from quandl) (2.28.0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.14->quandl) (2022.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (2.0.12)
Installing collected packages: more-itertools, inflection, quandl
Successfully installed inflection-0.5.1 more-itertools-9.1.0 quandl-3.7.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import quandl as q

In [9]:
import requests

In [10]:
pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.0.9-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 kB 2.4 MB/s eta 0:00:00a 0:00:01
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.9
Note: you may need to restart the kernel to use updated packages.

In [11]:
import xlsxwriter
import math

In [14]:
# set the API key

In [12]:
pip install nasdaq-data-link

Collecting nasdaq-data-link
  Using cached Nasdaq_Data_Link-1.0.4-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: numpy>=1.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (1.22.4)
Requirement already satisfied: requests>=2.7.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (2.28.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (1.16.0)
Requirement already satisfied: inflection>=0.3.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (0.5.1)
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (2.8.2)
Requirement already satisfied: more-itertools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (9.1.0)
Requirement already satisfied: pandas>=0.14 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nasdaq-data-link) (1.4.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=0.14->nasdaq-data-link) (2022.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->nasdaq-data-link) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->nasdaq-data-link) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->nasdaq-data-link) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.7.0->nasdaq-data-link) (1.26.9)
Installing collected packages: nasdaq-data-link
Successfully installed nasdaq-data-link-1.0.4
Note: you may need to restart the kernel to use updated packages.

In [13]:
import nasdaqdatalink

In [1]:
#Extracting data from the Quandl API

In [14]:
q.ApiConfig.api_key = "t3rDCnhuVLsmzTq2Yy8b"

In [34]:
#send a get request to query Microsoft's end of day stock prices from 1st #Jan, 2010 to 1st Jan, 2019

In [15]:
q.ApiConfig.api_key = 't3rDCnhuVLsmzTq2Yy8b'
q.get_table('QUOTEMEDIA/PRICES', date='2017-10-31,2017-10-30,2017-10-27', ticker='XOM')

,ticker,date,open,high,low,close,volume,dividend,split,adj_open,adj_high,adj_low,adj_close,adj_volume
None,,,,,,,,,,,,,,
0,XOM,2017-10-31,83.65,83.68,83.17,83.35,9754213.0,0.0,1.0,63.226346,63.249022,62.863541,62.999593,9754213.0
1,XOM,2017-10-30,83.71,83.95,83.41,83.54,7811022.0,0.0,1.0,63.271697,63.453100,63.044944,63.143204,7811022.0
2,XOM,2017-10-27,83.00,84.24,82.01,83.71,14866246.0,0.0,1.0,62.735048,63.672294,61.986762,63.271697,14866246.0

In [16]:
msft_data=q.get_table('QUOTEMEDIA/PRICES', ticker='XOM')

In [17]:
msft_data.head()

,ticker,date,open,high,low,close,volume,dividend,split,adj_open,adj_high,adj_low,adj_close,adj_volume
None,,,,,,,,,,,,,,
0,XOM,2017-10-31,83.65,83.68,83.1700,83.350,9754213.0,0.0,1.0,63.226346,63.249022,62.863541,62.999593,9754213.0
1,XOM,2017-10-30,83.71,83.95,83.4100,83.540,7811022.0,0.0,1.0,63.271697,63.453100,63.044944,63.143204,7811022.0
2,XOM,2017-10-27,83.00,84.24,82.0100,83.710,14866246.0,0.0,1.0,62.735048,63.672294,61.986762,63.271697,14866246.0
3,XOM,2017-10-26,83.37,83.65,83.1100,83.470,9152415.0,0.0,1.0,63.014710,63.226346,62.818191,63.090294,9152415.0
4,XOM,2017-10-25,83.45,83.73,82.9465,83.195,7654137.0,0.0,1.0,63.075178,63.286814,62.694610,62.882437,7654137.0

In [18]:
msft_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ticker      42 non-null     object
 1   date        42 non-null     datetime64[ns]
 2   open        42 non-null     float64
 3   high        42 non-null     float64
 4   low         42 non-null     float64
 5   close       42 non-null     float64
 6   volume      42 non-null     float64
 7   dividend    42 non-null     float64
 8   split       42 non-null     float64
 9   adj_open    42 non-null     float64
 10  adj_high    42 non-null     float64
 11  adj_low     42 non-null     float64
 12  adj_close   42 non-null     float64
 13  adj_volume  42 non-null     float64
dtypes: datetime64[ns](1), float64(12), object(1)
memory usage: 4.7+ KB

In [19]:
msft_data.describe()

,open,high,low,close,volume,dividend,split,adj_open,adj_high,adj_low,adj_close,adj_volume
count,42.000000,42.000000,42.000000,42.000000,4.200000e+01,42.0,42.0,42.000000,42.000000,42.000000,42.000000,4.200000e+01
mean,81.178571,81.581581,80.939443,81.337976,9.217467e+06,0.0,1.0,61.358332,61.662944,61.177588,61.478817,9.217467e+06
std,1.844482,1.818219,1.809087,1.777546,2.929739e+06,0.0,0.0,1.394141,1.374290,1.367388,1.343547,2.929739e+06
min,76.370000,76.850000,76.320000,76.570000,5.734007e+06,0.0,1.0,57.723802,58.086608,57.686010,57.874971,5.734007e+06
25%,79.895000,80.247500,79.715000,80.075000,7.254144e+06,0.0,1.0,60.388152,60.654587,60.252100,60.524204,7.254144e+06
50%,81.675000,81.930000,81.402500,81.775000,8.515198e+06,0.0,1.0,61.733555,61.926295,61.527587,61.809139,8.515198e+06
75%,82.682500,83.030000,82.352500,82.755000,9.916155e+06,0.0,1.0,62.495067,62.757723,62.245639,62.549866,9.916155e+06
max,83.710000,84.240000,83.410000,83.710000,1.857438e+07,0.0,1.0,63.271697,63.672294,63.044944,63.271697,1.857438e+07

In [20]:
msft_data

,ticker,date,open,high,low,close,volume,dividend,split,adj_open,adj_high,adj_low,adj_close,adj_volume
None,,,,,,,,,,,,,,
0,XOM,2017-10-31,83.65,83.6800,83.1700,83.350,9754213.0,0.0,1.0,63.226346,63.249022,62.863541,62.999593,9754213.0
1,XOM,2017-10-30,83.71,83.9500,83.4100,83.540,7811022.0,0.0,1.0,63.271697,63.453100,63.044944,63.143204,7811022.0
2,XOM,2017-10-27,83.00,84.2400,82.0100,83.710,14866246.0,0.0,1.0,62.735048,63.672294,61.986762,63.271697,14866246.0
3,XOM,2017-10-26,83.37,83.6500,83.1100,83.470,9152415.0,0.0,1.0,63.014710,63.226346,62.818191,63.090294,9152415.0
4,XOM,2017-10-25,83.45,83.7300,82.9465,83.195,7654137.0,0.0,1.0,63.075178,63.286814,62.694610,62.882437,7654137.0
5,XOM,2017-10-24,83.55,83.8065,83.3100,83.470,7551105.0,0.0,1.0,63.150762,63.344636,62.969359,63.090294,7551105.0
6,XOM,2017-10-23,83.15,83.7600,83.0401,83.240,9829846.0,0.0,1.0,62.848424,63.309489,62.765357,62.916450,9829846.0
7,XOM,2017-10-20,82.85,83.1300,82.6200,83.110,9574086.0,0.0,1.0,62.621671,62.833308,62.447827,62.818191,9574086.0
8,XOM,2017-10-19,82.35,83.0500,82.3300,82.740,7945461.0,0.0,1.0,62.243749,62.772840,62.228632,62.538528,7945461.0
9,XOM,2017-10-18,82.96,83.3910,82.5400,82.760,6367060.0,0.0,1.0,62.704814,63.030583,62.387360,62.553645,6367060.0
10,XOM,2017-10-17,82.63,82.9700,82.5400,82.960,6443821.0,0.0,1.0,62.455386,62.712373,62.387360,62.704814,6443821.0
11,XOM,2017-10-16,82.70,82.9500,82.5400,82.810,5734007.0,0.0,1.0,62.508295,62.697256,62.387360,62.591437,5734007.0
12,XOM,2017-10-13,82.73,83.0800,82.3600,82.410,7180001.0,0.0,1.0,62.530970,62.795515,62.251308,62.289100,7180001.0
13,XOM,2017-10-12,82.31,82.5000,82.1700,82.430,6647544.0,0.0,1.0,62.213515,62.357126,62.107697,62.304217,6647544.0
14,XOM,2017-10-11,82.16,82.7400,82.1400,82.600,7016193.0,0.0,1.0,62.100139,62.538528,62.085022,62.432710,7016193.0
15,XOM,2017-10-10,82.34,82.7350,82.0900,82.260,7218494.0,0.0,1.0,62.236191,62.534749,62.047230,62.175723,7218494.0
16,XOM,2017-10-09,81.84,82.1800,81.7600,82.030,7489870.0,0.0,1.0,61.858269,62.115256,61.797801,62.001879,7489870.0
17,XOM,2017-10-06,81.77,81.8900,81.3550,81.710,6070570.0,0.0,1.0,61.805360,61.896061,61.491685,61.760009,6070570.0
18,XOM,2017-10-05,81.72,82.2400,81.5900,82.020,7375872.0,0.0,1.0,61.767568,62.160606,61.669308,61.994321,7375872.0
19,XOM,2017-10-04,81.80,81.8700,81.4500,81.790,6357088.0,0.0,1.0,61.828035,61.880944,61.563490,61.820477,6357088.0
20,XOM,2017-10-03,81.41,81.9700,81.3000,81.760,6079970.0,0.0,1.0,61.533256,61.956529,61.450113,61.797801,6079970.0
21,XOM,2017-10-02,81.30,81.8190,81.2450,81.630,6777857.0,0.0,1.0,61.450113,61.842396,61.408542,61.699542,6777857.0
22,XOM,2017-09-29,81.94,82.0550,81.5750,81.980,9942991.0,0.0,1.0,61.933853,62.020775,61.657970,61.964087,9942991.0
23,XOM,2017-09-28,81.63,82.4500,81.5600,82.190,15581577.0,0.0,1.0,61.699542,62.319334,61.646633,62.122814,15581577.0
24,XOM,2017-09-27,80.89,81.4500,80.7900,81.430,9724266.0,0.0,1.0,61.140217,61.563490,61.064633,61.548373,9724266.0
25,XOM,2017-09-26,80.71,80.9950,80.5600,80.890,8754795.0,0.0,1.0,61.004165,61.219581,60.890789,61.140217,8754795.0
26,XOM,2017-09-25,80.03,81.0000,79.9800,80.980,10495577.0,0.0,1.0,60.490191,61.223360,60.452399,61.208243,10495577.0
27,XOM,2017-09-22,79.72,80.3000,79.6700,79.920,10204689.0,0.0,1.0,60.255880,60.694269,60.218087,60.407048,10204689.0
28,XOM,2017-09-21,80.49,80.5300,79.7600,79.890,11984080.0,0.0,1.0,60.837880,60.868113,60.286113,60.384373,11984080.0
29,XOM,2017-09-20,80.28,80.6600,80.2600,80.550,10606660.0,0.0,1.0,60.679152,60.966373,60.664035,60.883230,10606660.0
30,XOM,2017-09-19,80.06,80.3900,79.9850,80.220,9276572.0,0.0,1.0,60.512867,60.762295,60.456178,60.633802,9276572.0
31,XOM,2017-09-18,79.79,80.1400,79.7000,80.090,8594362.0,0.0,1.0,60.308789,60.573334,60.240763,60.535542,8594362.0
32,XOM,2017-09-15,80.12,80.2100,79.5500,80.070,16043707.0,0.0,1.0,60.558217,60.626243,60.127386,60.520425,16043707.0
33,XOM,2017-09-14,79.85,80.2300,79.7700,80.090,9066675.0,0.0,1.0,60.354139,60.641360,60.293672,60.535542,9066675.0
34,XOM,2017-09-13,79.50,79.7700,79.3800,79.770,8369659.0,0.0,1.0,60.089594,60.293672,59.998893,60.293672,8369659.0
35,XOM,2017-09-12,79.40,79.6900,79.2400,79.500,7643343.0,0.0,1.0,60.014010,60.233204,59.893075,60.089594,7643343.0
36,XOM,2017-09-11,79.41,79.4200,78.9000,79.250,12955773.0,0.0,1.0,60.021568,60.029126,59.636088,59.900633,12955773.0
37,XOM,2017-09-08,79.01,79.0400,78.6300,78.820,8436033.0,0.0,1.0,59.719230,59.741906,59.432010,59.575620,8436033.0
38,XOM,2017-09-07,79.02,79.3299,78.6100,79.030,9835647.0,0.0,1.0,59.726789,59.961025,59.416893,59.734347,9835647.0
39,XOM,2017-09-06,77.89,79.2250,77.5800,78.780,18574383.0,0.0,1.0,58.872685,59.881737,58.638374,59.545386,18574383.0
40,XOM,2017-09-05,76.64,77.3600,76.6100,77.180,12784845.0,0.0,1.0,57.927880,58.472088,57.905205,58.336036,12784845.0
41,XOM,2017-09-01,76.37,76.8500,76.3200,76.570,7361092.0,0.0,1.0,57.723802,58.086608,57.686010,57.874971,7361092.0

In [21]:
# Import numpy package
import numpy as np

In [25]:
# assign `Adj Close` to `daily_close`
daily_close = msft_data[['adj_close']]

In [26]:
# returns as fractional change
daily_return = daily_close.pct_change()

In [27]:
# replacing NA values with 0

daily_return.fillna(0, inplace=True)

In [28]:
print(daily_return)

      adj_close
None
0      0.000000
1      0.002280
2      0.002035
3     -0.002867
4     -0.003295
5      0.003305
6     -0.002755
7     -0.001562
8     -0.004452
9      0.000242
10     0.002417
11    -0.001808
12    -0.004830
13     0.000243
14     0.002062
15    -0.004116
16    -0.002796
17    -0.003901
18     0.003794
19    -0.002804
20    -0.000367
21    -0.001590
22     0.004288
23     0.002562
24    -0.009247
25    -0.006631
26     0.001113
27    -0.013090
28    -0.000375
29     0.008261
30    -0.004097
31    -0.001621
32    -0.000250
33     0.000250
34    -0.003996
35    -0.003385
36    -0.003145
37    -0.005426
38     0.002664
39    -0.003163
40    -0.020310
41    -0.007904

In [29]:
perc_change=daily_return*100

In [30]:
print(perc_change)

      adj_close
None
0      0.000000
1      0.227954
2      0.203495
3     -0.286704
4     -0.329460
5      0.330549
6     -0.275548
7     -0.156175
8     -0.445193
9      0.024172
10     0.241663
11    -0.180810
12    -0.483033
13     0.024269
14     0.206236
15    -0.411622
16    -0.279601
17    -0.390101
18     0.379391
19    -0.280419
20    -0.036679
21    -0.159002
22     0.428764
23     0.256160
24    -0.924687
25    -0.663146
26     0.111262
27    -1.308965
28    -0.037538
29     0.826136
30    -0.409683
31    -0.162054
32    -0.024972
33     0.024978
34    -0.399551
35    -0.338473
36    -0.314465
37    -0.542587
38     0.266430
39    -0.316336
40    -2.030972
41    -0.790360